# Generated by Django 5.2.3 on 2025-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=100)),
                ('specific_service', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('rating_working_environment', models.IntegerField(blank=True, null=True)),
                ('rating_courtesy', models.IntegerField(blank=True, null=True)),
                ('rating_professionalism', models.IntegerField(blank=True, null=True)),
                ('rating_waiting_time', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
